# Digital Ocean App Platform Specification
# This is a TEMPLATE - actual values are set per-client via DO API/Dashboard
#
# Deployment: $5/month tier (apps-s-1vcpu-0.5gb)
# - 1 shared vCPU
# - 512 MB RAM
# - 50 GB bandwidth
#
# Usage:
# 1. Create app via DO API or Dashboard
# 2. Set environment variables for the specific client
# 3. Connect client's domain via CNAME
# 4. Deploy

name: support-portal
region: nyc

services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/knowledge-base
      branch: main
      deploy_on_push: true

    # Build Configuration
    build_command: npm run build
    run_command: npm run start
    environment_slug: node-js

    # $5/month tier
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1

    # HTTP Configuration
    http_port: 3000

    # Health Check
    health_check:
      http_path: /support
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment Variables
    # These are set per-client - values here are placeholders
    # SECRET types are encrypted by DO and never exposed
    envs:
      # ===========================================
      # Security (Generate unique per client)
      # ===========================================
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "${SESSION_SECRET}"

      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET
        value: "${ENCRYPTION_KEY}"

      # ===========================================
      # Discord OAuth (Client provides these)
      # ===========================================
      - key: DISCORD_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
        value: "${DISCORD_CLIENT_ID}"

      - key: DISCORD_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "${DISCORD_CLIENT_SECRET}"

      - key: AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "${AUTH_SECRET}"

      - key: AUTH_URL
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
        value: "${AUTH_URL}"

      # ===========================================
      # Hygraph CMS (Client provides these)
      # ===========================================
      - key: CMS_SOURCE
        scope: RUN_TIME
        type: GENERAL
        value: "hygraph"

      - key: HYGRAPH_ENDPOINT
        scope: RUN_TIME
        type: GENERAL
        value: "${HYGRAPH_ENDPOINT}"

      - key: HYGRAPH_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: "${HYGRAPH_TOKEN}"

      # ===========================================
      # Jira Service Management (Client provides these)
      # ===========================================
      - key: ATLASSIAN_DOMAIN
        scope: RUN_TIME
        type: GENERAL
        value: "${ATLASSIAN_DOMAIN}"

      - key: ATLASSIAN_EMAIL
        scope: RUN_TIME
        type: GENERAL
        value: "${ATLASSIAN_EMAIL}"

      - key: ATLASSIAN_API_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: "${ATLASSIAN_API_TOKEN}"

      - key: JIRA_SERVICE_DESK_ID
        scope: RUN_TIME
        type: GENERAL
        value: "${JIRA_SERVICE_DESK_ID}"

      - key: JIRA_REQUEST_TYPE_ID
        scope: RUN_TIME
        type: GENERAL
        value: "${JIRA_REQUEST_TYPE_ID}"

      - key: JIRA_PROJECT_KEY
        scope: RUN_TIME
        type: GENERAL
        value: "${JIRA_PROJECT_KEY}"

      # ===========================================
      # Node Environment
      # ===========================================
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
        value: "production"

# Custom domain configuration (set per client)
# domains:
#   - domain: support.clientdomain.com
#     type: PRIMARY
#     minimum_tls_version: "1.2"

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
